CREATE TABLE acctmanager (
    acctmanager_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name     VARCHAR2(50)  NOT NULL,
    last_name      VARCHAR2(50)  NOT NULL,
    email          VARCHAR2(100),
    phone          VARCHAR2(25)
);

SELECT c.first_name, c.last_name, c.customer_id, o.shipped_date
FROM sales_customers c
JOIN sales_orders o ON c.customer_id = o.customer_id;

SELECT s.first_name, s.last_name, o.customer_id, o.shipped_date
FROM sales_staffs s
JOIN sales_orders o ON s.staff_id = o.staff_id;

SELECT 
    c.first_name || ' ' || c.last_name AS customer_name,
    o.order_id,
    c.customer_id,
    o.order_date,
    s.first_name || ' ' || s.last_name AS staff_name
FROM sales_orders o
JOIN sales_customers c ON o.customer_id = c.customer_id
JOIN sales_staffs s ON o.staff_id = s.staff_id;

--PART B

SELECT DISTINCT c.first_name, c.last_name, c.customer_id, o.store_id
FROM sales_customers c
JOIN sales_orders o ON c.customer_id = o.customer_id
WHERE o.store_id = 2;

SELECT DISTINCT s.first_name, s.last_name, oi.discount
FROM sales_staffs s
JOIN sales_orders o ON s.staff_id = o.staff_id
JOIN sales_order_items oi ON o.order_id = oi.order_id
WHERE oi.discount > 0.05;


SELECT * FROM USER_SYS_PRIVS;

SELECT * FROM SESSION_PRIVS;

-- Note: Running these commands with the current privileges will produce an ORA-01031 error.
GRANT CREATE SESSION, CREATE TABLE TO COMP122_W25_YUR_111;
GRANT SELECT, INSERT, UPDATE ON sales_customers TO COMP122_W25_YUR_111;



--B5
-- Create a new role named MY_ROLE.
CREATE ROLE my_role;

-- Grant five privileges to the role.
GRANT CREATE SESSION     TO my_role;
GRANT CREATE TABLE       TO my_role;
GRANT SELECT ON sales_customers TO my_role;
GRANT INSERT ON sales_customers TO my_role;
GRANT UPDATE ON sales_customers TO my_role;


-- B5: Attempt to create a role named MY_ROLE and grant it five privileges.
-- Note: I lack the required privileges to create a role or grant privileges to it,
--so I will also encounter an error when running these commands.
CREATE ROLE my_role;

GRANT CREATE SESSION     TO my_role;
GRANT CREATE TABLE       TO my_role;
GRANT SELECT ON sales_customers TO my_role;
GRANT INSERT ON sales_customers TO my_role;
GRANT UPDATE ON sales_customers TO my_role;

















